//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Guid_no.wcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetail", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class LoginDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string App_VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Device_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMEI_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Login_ViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string App_Version {
            get {
                return this.App_VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.App_VersionField, value) != true)) {
                    this.App_VersionField = value;
                    this.RaisePropertyChanged("App_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Device_ID {
            get {
                return this.Device_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Device_IDField, value) != true)) {
                    this.Device_IDField = value;
                    this.RaisePropertyChanged("Device_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI_No {
            get {
                return this.IMEI_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.IMEI_NoField, value) != true)) {
                    this.IMEI_NoField = value;
                    this.RaisePropertyChanged("IMEI_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login_Via {
            get {
                return this.Login_ViaField;
            }
            set {
                if ((object.ReferenceEquals(this.Login_ViaField, value) != true)) {
                    this.Login_ViaField = value;
                    this.RaisePropertyChanged("Login_Via");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeMasterData.EmployeeMasterSUB", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EmployeeMasterDataEmployeeMasterSUB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityHandleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpDocCopyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IFSCCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JoinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeaveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldCompanyExpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepotingToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesPercentagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiftIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkOverviewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccNo {
            get {
                return this.BankAccNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccNoField, value) != true)) {
                    this.BankAccNoField = value;
                    this.RaisePropertyChanged("BankAccNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityHandleID {
            get {
                return this.CityHandleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CityHandleIDField, value) != true)) {
                    this.CityHandleIDField = value;
                    this.RaisePropertyChanged("CityHandleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityID {
            get {
                return this.CityIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CityIDField, value) != true)) {
                    this.CityIDField = value;
                    this.RaisePropertyChanged("CityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryIDField, value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateField, value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpCode {
            get {
                return this.EmpCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpCodeField, value) != true)) {
                    this.EmpCodeField = value;
                    this.RaisePropertyChanged("EmpCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpDocCopy {
            get {
                return this.EmpDocCopyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpDocCopyField, value) != true)) {
                    this.EmpDocCopyField = value;
                    this.RaisePropertyChanged("EmpDocCopy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpImage {
            get {
                return this.EmpImageField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpImageField, value) != true)) {
                    this.EmpImageField = value;
                    this.RaisePropertyChanged("EmpImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IFSCCode {
            get {
                return this.IFSCCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IFSCCodeField, value) != true)) {
                    this.IFSCCodeField = value;
                    this.RaisePropertyChanged("IFSCCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JoinDate {
            get {
                return this.JoinDateField;
            }
            set {
                if ((object.ReferenceEquals(this.JoinDateField, value) != true)) {
                    this.JoinDateField = value;
                    this.RaisePropertyChanged("JoinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeaveDate {
            get {
                return this.LeaveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LeaveDateField, value) != true)) {
                    this.LeaveDateField = value;
                    this.RaisePropertyChanged("LeaveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldCompany {
            get {
                return this.OldCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.OldCompanyField, value) != true)) {
                    this.OldCompanyField = value;
                    this.RaisePropertyChanged("OldCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldCompanyExp {
            get {
                return this.OldCompanyExpField;
            }
            set {
                if ((object.ReferenceEquals(this.OldCompanyExpField, value) != true)) {
                    this.OldCompanyExpField = value;
                    this.RaisePropertyChanged("OldCompanyExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherMobile {
            get {
                return this.OtherMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherMobileField, value) != true)) {
                    this.OtherMobileField = value;
                    this.RaisePropertyChanged("OtherMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinCode {
            get {
                return this.PinCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PinCodeField, value) != true)) {
                    this.PinCodeField = value;
                    this.RaisePropertyChanged("PinCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryID {
            get {
                return this.QueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryIDField, value) != true)) {
                    this.QueryIDField = value;
                    this.RaisePropertyChanged("QueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUserID {
            get {
                return this.RUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RUserIDField, value) != true)) {
                    this.RUserIDField = value;
                    this.RaisePropertyChanged("RUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUserType {
            get {
                return this.RUserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RUserTypeField, value) != true)) {
                    this.RUserTypeField = value;
                    this.RaisePropertyChanged("RUserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepotingTo {
            get {
                return this.RepotingToField;
            }
            set {
                if ((object.ReferenceEquals(this.RepotingToField, value) != true)) {
                    this.RepotingToField = value;
                    this.RaisePropertyChanged("RepotingTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIDField, value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryAmt {
            get {
                return this.SalaryAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryAmtField, value) != true)) {
                    this.SalaryAmtField = value;
                    this.RaisePropertyChanged("SalaryAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalaryType {
            get {
                return this.SalaryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryTypeField, value) != true)) {
                    this.SalaryTypeField = value;
                    this.RaisePropertyChanged("SalaryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesPercentages {
            get {
                return this.SalesPercentagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesPercentagesField, value) != true)) {
                    this.SalesPercentagesField = value;
                    this.RaisePropertyChanged("SalesPercentages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiftID {
            get {
                return this.ShiftIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiftIDField, value) != true)) {
                    this.ShiftIDField = value;
                    this.RaisePropertyChanged("ShiftID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Skills {
            get {
                return this.SkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillsField, value) != true)) {
                    this.SkillsField = value;
                    this.RaisePropertyChanged("Skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StateIDField, value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalExperience {
            get {
                return this.TotalExperienceField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalExperienceField, value) != true)) {
                    this.TotalExperienceField = value;
                    this.RaisePropertyChanged("TotalExperience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedDateField, value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkOverview {
            get {
                return this.WorkOverviewField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOverviewField, value) != true)) {
                    this.WorkOverviewField = value;
                    this.RaisePropertyChanged("WorkOverview");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryMasterData.CategoryMasterSUB", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CategoryMasterDataCategoryMasterSUB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImgPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainCategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeID {
            get {
                return this.AttributeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeIDField, value) != true)) {
                    this.AttributeIDField = value;
                    this.RaisePropertyChanged("AttributeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIDField, value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgPath {
            get {
                return this.ImgPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImgPathField, value) != true)) {
                    this.ImgPathField = value;
                    this.RaisePropertyChanged("ImgPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCategoryID {
            get {
                return this.MainCategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MainCategoryIDField, value) != true)) {
                    this.MainCategoryIDField = value;
                    this.RaisePropertyChanged("MainCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUserID {
            get {
                return this.RUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RUserIDField, value) != true)) {
                    this.RUserIDField = value;
                    this.RaisePropertyChanged("RUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUserType {
            get {
                return this.RUserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RUserTypeField, value) != true)) {
                    this.RUserTypeField = value;
                    this.RaisePropertyChanged("RUserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxID {
            get {
                return this.TaxIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxIDField, value) != true)) {
                    this.TaxIDField = value;
                    this.RaisePropertyChanged("TaxID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.V2.testbuds.co.in/", ConfigurationName="wcf.IGrubrrV2")]
    public interface IGrubrrV2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.V2.testbuds.co.in/IGrubrrV2/BranchAuthentication", ReplyAction="http://www.V2.testbuds.co.in/IGrubrrV2/BranchAuthenticationResponse")]
        string BranchAuthentication(Test_Guid_no.wcf.LoginDetail LoginDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.V2.testbuds.co.in/IGrubrrV2/AddStaff", ReplyAction="http://www.V2.testbuds.co.in/IGrubrrV2/AddStaffResponse")]
        string AddStaff(Test_Guid_no.wcf.EmployeeMasterDataEmployeeMasterSUB EmployeeMasterSUB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.V2.testbuds.co.in/IGrubrrV2/ManageCategory", ReplyAction="http://www.V2.testbuds.co.in/IGrubrrV2/ManageCategoryResponse")]
        string ManageCategory(Test_Guid_no.wcf.CategoryMasterDataCategoryMasterSUB[] CategoryMasterSUB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrubrrV2Channel : Test_Guid_no.wcf.IGrubrrV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrubrrV2Client : System.ServiceModel.ClientBase<Test_Guid_no.wcf.IGrubrrV2>, Test_Guid_no.wcf.IGrubrrV2 {
        
        public GrubrrV2Client() {
        }
        
        public GrubrrV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrubrrV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrubrrV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrubrrV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string BranchAuthentication(Test_Guid_no.wcf.LoginDetail LoginDetail) {
            return base.Channel.BranchAuthentication(LoginDetail);
        }
        
        public string AddStaff(Test_Guid_no.wcf.EmployeeMasterDataEmployeeMasterSUB EmployeeMasterSUB) {
            return base.Channel.AddStaff(EmployeeMasterSUB);
        }
        
        public string ManageCategory(Test_Guid_no.wcf.CategoryMasterDataCategoryMasterSUB[] CategoryMasterSUB) {
            return base.Channel.ManageCategory(CategoryMasterSUB);
        }
    }
}
